import { useState, useEffect } from "react";
import Head from "next/head";
import Map from "../components/MapView";
import SidePanel from "../components/SidePanel";
import { ActiveContextProvider } from "../components/ActiveContext";
export default function Home() {
  const [markers, setMarkers] = useState([]);

  const fetchData = async () => {
    const url = "https://api.jsonbin.it/bins/njA6q0uq";
    try {
      const apiData = await fetch(url);
      const json = await apiData.json();
      setMarkers(json.places);
    } catch (err) {
      console.log("Failed to get data", err);
    }
  };
  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div>
      <Head>
        <title>Map App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row w-full h-screen">
        <ActiveContextProvider>
          <section className="flex w-3/5 bg-yellow-500">
            <div className="relative h-full w-full">
              <Map markers={markers} />
            </div>
          </section>
          <section className="flex w-2/5">
            <SidePanel markers={markers} />
          </section>
        </ActiveContextProvider>
      </main>
    </div>
  );
}
